#!/usr/bin/python

"""
Topology Dict, generated by GraphML-Topo-to-Dict.
"""

graph = {
    0: {1: 5},
    1: {0: 5, 2: 10},
    2: {1: 10, 3: 5, 4: 20},
    3: {2: 5, 4: 20},
    4: {2: 20, 3: 20},
}